### ISSUE TITLE
needs_title_from_content should detect case after dot

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinxcontrib-needs#107]
In my conf.py I have `needs_title_from_content = True`.
The need
```
.. vdaisa_req::
:id: VDAISA_REQ_01_02_07_01

Es existiert ein Maßnahmenplan bzw. etwas anderes der Maßnahmenumsetzung.
```
renders to
![image](https://user-images.githubusercontent.com/839934/71515706-0b265d80-28a5-11ea-89fd-b65cc8cac47b.png)

The sentence recognition should detect that the next word after `max.` starts with a lower case letter. Sentences in major languages like English/German/French/Italian/Spanish starts with a capital letter, so the logic can assume that the dot does not mark the end of a sentence.

**Comment by danwos** [comment]
I think  there are too many corner cases for this rule.
A sentence can easily start with a lower case e.g. as function name or because the user doesn't want to use uppercase :)

Also the workarounds from #106 are working for this as well.
So I see a lot of possible problems for a not clearly given benefit....

**Comment by ubmarco** [comment]
I'm ok with this and will close the issue.
