### ISSUE TITLE
Sphinx linkcheck builder fails with AttributeError

### ISSUE THREAD

**Issue by bunder** [useblocks/sphinxcontrib-needs#134]
Starting with v0.5.0, building a project with `linkcheck` builder fails with

```
Exception occurred:
  File "/home/aleontiev/.local/share/virtualenvs/bug-needs-jx7r6-Ft/lib/python3.6/site-packages/sphinx/builders/linkcheck.py", line 290, in write_doc
    uri = imgnode['candidates'].get('?')
AttributeError: 'str' object has no attribute 'get'
```

Full Sphinx log: https://hastebin.com/uzowuzavav.shell

**Comment by bunder** [comment]
I can provide minimal project to reproduce though it is really trivial.

**Comment by danwos** [comment]
Thanks for reporting this.

Was able to reproduce it.
I set the image-candidates wrong so that linkcheck was not able to handle them.
Should be fixed.

Can you give it a try by installing latest version of master?
Thanks.

Final release may need 2-3 days, as I need to implement some more stuff for 0.5.3.

**Comment by bunder** [comment]
> Can you give it a try by installing latest version of master?

linkcheck builder works with master branch. Thank you!
