### ISSUE TITLE
A node can only be in one page, else it will be cut when generate latexpdf 

### ISSUE THREAD

**Issue by sophiali2008** [useblocks/sphinxcontrib-needs#141]
Hello,
I used the extension needs 0.5.3 in my project, it is perfectly fit in html. 
But when I generate latexpdf, the content is cut if it is more than one page. Is it possible to generate it like a longtable which adjust the content in different continues pages ?

**Comment by danwos** [comment]
Hi,
thanks for the bug report. :+1: 

To be honest, I currently don't know how to deal with this.
I thought docutils or the related latex-builder is handling this, as the extension only creates docutils-nodes from type table and the builder then decides what do do with it.

I have to check, if there is maybe another table-type, which is supported better by latexpdf.

**Comment by Juzamn** [comment]
Same problem for me.
Is it possible to consider to use an other type of table than docutils-nodes please?

Otherwise, it would be great (and maybe more simple) to add an option to display Needs without tables but just with a combinaision of titles and formatted texts! Thus, Needs will be properly displayed over several pages with this kind of formatting.

**Comment by hkaimio** [comment]
I have a similar problem which is currently preventing me from upgrading from 0.4. My documents have some needs items that include very long (multi-page) tables. They show up OK with Needs 0.4 but the table based need layout introduced in 0.5 broke LaTeX rendering. Apparently Sphinx generates a "longtable" inside "tabular" environment which does not work (I am not an Latex expert but this is my understanding)

I'd also like to cast a vote for a non-table based Needs layout. In our case we mostly use Needs to embed traceability information to documentation but for printed and web rendering we usually want to hide most of it (we also use the "needs" builder extensively to get this data out in machine readable form)

**Comment by danwos** [comment]
Being based on docutils-nodes gave me the freedom to not write code for specific output formats.

Throwing out table based format is a lot of work and would need weeks of refactoring.
For me this is not an option.

The only chance of solving this is by writing a special handler for the latex builder.
Doable and a lot of other extensions are doing it. 
But I don't know nearly nothing about Latex, so that I'm afraid to be the wrong person to deal with it.

Also I'm not sure of this problem should be really solved in ``sphinx-needs`` or directly in ``docutils`` or even ``sphinx``.

So I would be more than happy if somebody else could step in and provide a PR for this.

**Comment by danwos** [comment]
I close this, as I see no way to solve this in Sphinx-Needs without changing the complete layout related code and without introducing output format specific builder code.
Both tasks are too much work.
