### ISSUE TITLE
Contributing page for docs

### ISSUE THREAD

**Issue by danieleades** [useblocks/sphinxcontrib-needs#152]
This is a really useful library, and I can't really see anything else out there for plain-text requirements management (with the *possible* exception of [doorstop](https://github.com/doorstop-dev/doorstop))

I can see this being adopted in my workplace.

Do you have any on-boarding for contributions? style guides, build instructions, commands for performing local testing?

additionally,
- would you be interested in migrating to [Poetry](https://python-poetry.org/)?
- would you be interested in adding 'typing' (and mypy linting)?
- is there any kind of roadmap of planned development?

**Comment by danwos** [comment]
Thanks for your feedback.

There is no on-boarding for contribution (which is for sure a bug in our documentation). 

We use tox for running and testing everything, which is needed for a git commit / contribution / release.
So the ``tox.ini`` contains everything what is used. Currently only nosetests and flake8.

I'm open to support Poetry beside pip. Supporting only one of those would maybe lock out some users.
So we need to find a way to keep files for both tools in sync. But yes, in general  I'm open to use Poetry as well (already doing it in other projects).
Also using ``typing`` and the usage of ``mypy`` is a great idea (also already part of some other projects).

However, there is no roadmap, only open issues.
This is mainly because this extension gets normally extended by feature-based pull-requests, which a user strongly needs for his/her daily work. There is no fix dev-team with available resources.
This applies also for me, as most features get integrated by needs inside some internal projects at work.
And honestly, thanks of corona, all documentation-related projects are on hold currently.
So time is rare and I don't know, if and when someone shows up who wants to integrate ``poetry`` or ``typing``.

But the above is not valid for bugs, issues, questions or feedback for specifications/ideas/PRs.
This kind of stuff I try to answer/implement asap.

So any help is highly appreciated and I'm willing to support you (and all others) where ever it is needed.

**Comment by danieleades** [comment]
How do you feel about adding formatting?

Specifically-
- [black](https://github.com/psf/black)
- [isort](https://pycqa.github.io/isort/)

**Comment by danwos** [comment]
All there now. Thanks for contributing. :+1:
