### ISSUE TITLE
Code Duplication

### ISSUE THREAD

**Issue by danieleades** [useblocks/sphinxcontrib-needs#176]
there's a lot of duplication of logic in this library. This makes refactoring challenging, and is a maintenance burden.

Some quick static analysis (using [jscpd](https://github.com/kucherenko/jscpd)) indicates that at the time of writing 36.15% of this codebase is duplicated. Obviously this is only a rough estimate, and probably includes a lot of test files which will remain duplicated.

I thought it might be useful to create this issue to track pull requests, discussion, and progress around this effort.

- [x] #171 
- [x] #167 
- [x] #172 
- [x] #175 
- [x] #174 
- [x] #198 
- [ ] #201 
- [ ] #202 
- [ ] #212

**Comment by danieleades** [comment]
the 'filtering' logic is probably a good next target- it's complex, and re-implemented in a couple of different locations.

i'm reluctant to do any large-scale refactoring until I can get all the tests running (and passing) locally. This is causing me some headaches.

**Comment by danwos** [comment]
Ohh yeah, that's true.
A lot of code was not written so nicely and there is a lot of room for optimization.
I activated travis CI builds for PRs (somehow missed that) so that it is easier to "trust" a PR if the tests are all green.

I'm absolutely not familiar with static code analysis (beside the features in my PyCharm IDE), so fell free to open issues whenever a problem shows up. In 4-5 weeks a get some room to spend more time on this lib and my goal is to fix a lot of the open stuff :)

**Comment by danieleades** [comment]
ah no problem! I use a few different tools, but if you might want to take a look at `PyLint`- it's a bit of an all-in-one.

**Comment by danieleades** [comment]
the same copy-paste detection now returns 35.55% duplication...
not a massive improvement.

at the same time, the project is now 323 lines of code lighter, and that's despite formatting changes that made the argument lists of a number of functions vertical.

I'm hoping along the way I can build enough knowledge to tackle my own blocking bugs - ie

- #166 
- #164
