### ISSUE TITLE
Support migration to Sphinx 4.x

### ISSUE THREAD

**Issue by romintomasetti** [useblocks/sphinxcontrib-needs#243]
A first error when trying with Sphinx 4.x: `could not import ENOENT`.

It makes sense because it disappeared in Sphinx 4.x, see the file `https://github.com/sphinx-doc/sphinx/blob/4.x/sphinx/util/osutil.py`.

**Comment by danwos** [comment]
Thanks for the report.

Will test it with the Sphinx 4.0 beta in the next days.

For the upcoming release 0.6.1 I have dropped Sphinx >= 4.0 support in ``pyproject.toml``.

**Comment by danwos** [comment]
After some analysis, Sphinx-Needs itself is not using ``ENOENT``.
But inside ``needflow.py`` it imports ``plantuml`` from extension ``sphinxcontrib-plantuml``, which is using it.

I created a PR in ``sphonxcontrib-plantuml`` which should fix it:
https://github.com/sphinx-contrib/plantuml/pull/57

**Comment by danwos** [comment]
Fixed by https://github.com/sphinx-contrib/plantuml/commit/c5e56fb2b28366a37519a550de894bc55da4fec5
But it got not released yet.

I keep this open to remind me to set a specific sphinxcontrib-plantuml version, when it go released

Open Task (after new sphinx-plantuml release):
- Check Sphinx 4.0 support again
- Force usage of specific sphinx-plantuml version if sphinx-needs is sued with sphinx >=  4.0

**Comment by asbach** [comment]
The fix was included in 0.21 :-) https://github.com/sphinx-contrib/plantuml/releases/tag/0.21

**Comment by danwos** [comment]
@asbach Thanks for thr hint. 👍 
Will ckeck and release support for sphinx 4.0 soon.

**Comment by danwos** [comment]
Pinned plantuml version to ^021 already with #283 to pass CI.
Sphinx 4.0 should be supported now.
