### ISSUE TITLE
Use '[' ... ']' to refer need-IDs; not '(' ...')'. Or/Better: make it an option

### ISSUE THREAD

**Issue by AlbertMietus** [useblocks/sphinxcontrib-needs#25]
Currently a need-ref containing both the "text" and the ID use (hardcode) round-braces around the ID.
However, the text-itself may use them to. Which results in a *bad looking result*.

Also, most enviroments, including Sphinx, use square-barces ``[...]`` for references/IDs.

Therefore, please change this. It would be simple to change this and make it configuable

Example/fix
=========
In file `need_ref.py` (line 28), replace
```
link_text = "{title} ({id})".format(title=target_need["title"], id=target_need["id"])
```
by
```
prefix, suffix = app.config.needs_id_braces
link_text = "{title} {prefix}{id}{suffix}".format(title=target_need["title"], id=target_need["id"], prefix=prefix, suffux=suffix)
```

And add the configuration needs_id_braces: a tuple of 2 string,

Thanks

[[This is a feature **request**, not a bug -- But I can't find out how to markt it as such ]]

**Comment by danwos** [comment]
Great idea.
Making this somehow configurable was also on my own wishlist.

The final solution got a little bit more complex, but it should fully support your use case.
Please see [this sphinx-needs configuration page](http://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-role-need-template) for a detailed description.

This and all other changes from the last hours are already available on [pypi](https://pypi.python.org/pypi/sphinxcontrib-needs/) (version 0.1.48)

Please let me know, if there are any problems or not fulfilled use cases.

**Comment by AlbertMietus** [comment]
Thanks, But let try to make it even better:-)

I have two _design improvement_ suggestion on this

1)  Use a single ('html_theme' alike) config **template** item.
2) Can we use jinja2 style templates (either as string, or in a file)?

Ad1
There are several "templates" already, and probably more will follow. Also, this is more an advance config item. Which probably will be maintained for many projects -- all using the same "house style". Putting them all in 1 dict make this a lot easier: E.g, Put them a separate "std" file and import that once in conf.py (I do that for e.g the HTML_theme to -- Giving all related projects the same feel)

Ad2
I like the template idea/concept. Many people do. However, using a different format/semantics for every time makes it harder. Therefore, I prefer to stick to the template (engine/semantics) which us used at the hart of Sphinx: jinja2

Note: Jinja2 isn't HTML oriented. In this case we would translate to strikt rst format. Filling in values in a rat-boilterplate. 

Note: This also removes the current "no rst bold (**), etc" rule

Thanks agains

**Comment by danwos** [comment]
I'm a big jinja2 fan, but there are 2-3 problems:
1. jinja is not rst. If we want style-tags like **bold** we need to support rst, not jinja only.
2. I personally don't see big advantages to support jinja (not rst!) for text-representation of a role, because this text is normally relative short and part of a sentence. So most jinja features (if, for, ...) doesn't make sense in this context. (For the need itself we already have fully jinja2/rst support)
3. For me the sphinx-state-machine is a beast and poorly documented. The handling of referenced needs must be done after all rst-files have been parsed and the doc-tree is complete.
Therefore I'm not really sure, if rst-content can be used/is supported in the needed state. I need to dive deeper into sphinx to get an answer on this... (Will take some time).

However, supporting RST/jinja2 is a great idea, therefore i created #28.

The template idea is nice, but would add another level of abstraction to the configuration (Create another file. Then add config params). Currently it's very easy to set needed params only.
Maybe I misunderstood your use case, but I think you can fulfill your needs with a simple import statement:

1. But each sphinx-needs parameter to another python file, e.g. conf_needs.py
2. Import this file inside conf.py: `from conf_needs import *`
3. Your sphinx project is configured.
4. (Bonus) Share conf_needs.py easily by:

* Putting it on a network-folder and add it to your sys.path in conf.py
* Adding a file-download-command at the beginning of your conf.py and add the downloaded file to sys.path (This would support ftp, git, svn, ...)
* Create a simple python package, store it on a company internal pypi clone and add it as project dependency / install it via pip.

**Comment by AlbertMietus** [comment]
The template-in-one-dict idea is doesn’t need more abstraction. Nor more files; it just make it simpler for reuse.

Suppose we combine all template-style config values into one; a dict where the values are the real setting (the template-strings), and the key denotes which role/directive.  Let’s call that setting ``needs_templates``.

Then, it is simple to use a line like 
```
from my_std_conf import needs_templates
```
Remember, conf.py is std-python, so include just works

Note:   That would be possible to, for small, single template setting too; but then one has to import a list of var-names (Or ``*``, which is bad) And maintain that line!  The 1 dict-setting is easier: only the maintainer of the std-conf-file has to act; not all projects using the std-template (This when a needs defines a new template setting)

---Albert 
Verstuurd via mijn iPad; excuus voor typo's etc.

**Comment by danwos** [comment]
I'm personally not a big fan of this idea, because it makes simple config changes more complex.
Imagine you need to change only one need-config parameter. It would look like this:
```
needs_template = {"needs_css": "dark.css"}
```
instead of
```
needs_css = "dark.css"
```
I understand the problem with your complex use case, but I think it is a very rare case and most users would expect the standard sphinx way.

Maybe for your case, something like this could be workaround:
**needs_conf.py**
```
needs_template = {
    "needs_css": "dark.css",
    "needs_types": [
               dict(directive="req", title="Requirement", prefix="R_", color="#BFD8D2", style="node"),
               dict(directive="spec", title="Specification", prefix="S_", color="#FEDCD2", style="node"),
               dict(directive="impl", title="Implementation", prefix="I_", color="#DF744A", style="node"),
               dict(directive="test", title="Test Case", prefix="T_", color="#DCB239", style="node"),
               dict(directive="need", title="Need", prefix="N_", color="#9856a5", style="node")
           ]
}

```
**conf.py**
```
import sys
from needs_conf import needs_template

module = sys.modules[__name__]
for name, value in needs_template.iteritems():
    setattr(module, name, value)
```
Some more ideas how to set the vars:
https://stackoverflow.com/questions/1429814/how-to-programmatically-set-a-global-module-variable

**Comment by AlbertMietus** [comment]
No, no, no. That is not what I (wanted to) suggest :-)

The new **needs_templates** (dict) setting is ONLY for python/ninja/other-settings which value is a _template_-**string**. So, the current ``needs_template``, ``needs_diagram_template``, ``needs_role_need_template``. And possible future ones.

The _simple_/_single_ settings (like ``needs_css`, ``needs_types``, etc) are fine. I fully agree.

Sorry for the confusion; I hope my which is more clear now.

On the use-case argument: The "simple" setting are indeed simple; typical pro project. The templates are more advanced. Probably most (small) projects don't care -- or like to inherit from a program/overall-projects (setting) -as I suggested.
