### ISSUE TITLE
Table details not collapsable in material theme

### ISSUE THREAD

**Issue by dstadelm** [useblocks/sphinxcontrib-needs#306]
Using the material theme (and others) the details of requirements et al. are static and the arrow items are displayed incorrectly. Is there a possibility to work around this issue?
![image](https://user-images.githubusercontent.com/3010527/123417669-57488000-d5b8-11eb-8d2e-1fbc7f80d3f8.png)

**Comment by danwos** [comment]
It looks like no sphinx-needs js code gets executed. 
Are you using the latest versions?

**Comment by dstadelm** [comment]
Boah, your fast :-)

sphinx-4.0.0 
sphinxcontrib-needs-0.6.3

**Comment by dstadelm** [comment]
And it works with rtd theme, and also alabaster, but not with material

**Comment by danwos** [comment]
Thanks for the details.
Will need some time to check how material is handling js and co. and how a fix/workaround may look like.

**Comment by twodrops** [comment]
I remember having the same issue for alabaster and RTD sometime ago https://github.com/useblocks/sphinxcontrib-needs/issues/242

**Comment by danwos** [comment]
Sphinx-Material is deleting ALL css table classes by default.
So the css and js code from Sphinx-Needs can not find the needed tables in the html document anymore.

I created a PR for Sphinx-Material to be able to deactivate this handling for specific tables:
https://github.com/bashtage/sphinx-material/pull/120

With #376 Sphinx-Needs sets a specific class, so that Sphinx-Material does not care about Sphinx-Needs tables.
However, this will only work, if the PR for  Sphinx-Material gets merged too.
