### ISSUE TITLE
Extension of single need with needextend affects all needs

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#308]
If I extend a single need without "quotes" for the ID within filter

```
... needextend:: MY_NEED_ID
    :status: new status
```

It throws the following error

>WARNING: Filter MY_NEED_ID not valid: Error: Filter MY_NEED_ID not valid: Error: name 'MY_NEED_ID' is not defined

If I use quotes, it matches all existing needs and extends all of them (even the ones with different ID)

```
... needextend:: "MY_NEED_ID"
    :status: new status
```

**Comment by danwos** [comment]
The ID must fully match the regex of ``needs_id_regex``.
So the regex must include ``^...$`` for defining start and end of the string.
But this is also missing in some of my docs, so that the ID detection does not work.

Removed the regex check and just look, if there is a need with the given string as ID.
If not, it gets interpreted as filter string.

That's also the reason why ``MY_NEED_ID`` returns all needs.
It gets interpreted as string, which is always true :)

**Comment by twodrops** [comment]
@danwos The following works as expected now. 

```
... needextend:: MY_NEED_ID
    :status: new status
```

But I guess I am getting picky here. The following matches the regex and returns true for all needs I guess.

```
... needextend:: 'MY_NEED_ID'
    :status: new status
```
or

```
... needextend:: "MY_NEED_ID"
    :status: new status
```

I converted the above from id =="" form to write it in short. Don't know if a typical user might do it as well and then not remove the "".

```
... needextend:: id == "MY_NEED_ID"
    :status: new status
```

**Comment by danwos** [comment]
This is the expected behavior for all your cases :)
As the last 3 examples get all interpreted as filter string.

But I see your point, that a user can make a mistake here quite easy.
We could print some warnings, if:
* argument starts with ``"`` or ``'``
* Filter result amount is bigger than x needs

But to be honest, for each check, which comes in my mind, I also see some valid use cases and we would have a false positive warning.

I would not do anything here, as it is a problem in the rst code, which impact is so huge, that the user should notice it  or he/she can filter for it.

**Comment by twodrops** [comment]
@danwos Yes, I am with you on that. I agree that each check is costly and we need to add it only if it results in really corrupt data. So I would also leave it like this for now. When it comes to ISO classification/qualification, the usecase might have shown as foolproof, for example, how do you prevent the case that the wrong requirement go linked and then got implemented in a wrong unit. But that's later.
