### ISSUE TITLE
needextend does not work depending on file order

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#310]
If the ``need`` and ``needextension`` are in the same file, the order between them does not seem to matter and both of the following works.

```rst
.. need:: MY_NEED_ID

.. needextend:: MY_NEED_ID
   :status: my-status
```
or 

```rst
.. needextend:: MY_NEED_ID
   :status: my-status

.. need:: MY_NEED_ID

```

If they are split into different files (that is, `need` in one and `needextend` in the other), the file order (based on filename) seems to matter.  The ``needextend`` does not do any extension, if filenames are changed so that they are alphabetically sorted differently.

**Comment by twodrops** [comment]
When it doesn't work, the ``is_modified`` flag return ``FALSE`` in the rst page where ``need`` is defined and ``TRUE`` in the page where ``needextension`` is defined

**Comment by danwos** [comment]
Ohh sh**, you are right.
I have extended my test cases and can confirm this.

The problem is the sphinx event system, which triggers the events per page.
So a need on page_1 gets created in docutils node-tree before needextend of page_2 gets executed.

So a solution may be to remove ``needextend`` from any events and let the need-creation code take a look into the already fully collected needextend information and execute the modification then per need.
This sounds doable.

Thanks for reporting and testing it so deeply. :+1: I'm on it.

**Comment by twodrops** [comment]
@danwos Thanks to you for verifying this so fast and explaining the reason. I wish I had the time and permission (from my company) and of course python-skills to contribute code here rather than only reporting :)

**Comment by twodrops** [comment]
@danwos 
>So a need on page_1 gets created in docutils node-tree before needextend of page_2 gets executed.

This means if `needextend` on page_1 gets executed and then `need` gets created on page_2 it works. If yes, it explains why the filename change had an impact.

**Comment by danwos** [comment]
Yes right.
The PR #311 fixes this, by handling **all** ``needextend`` already on the first page and not only the once which are defined on this page. And ``needextend`` handling gets always done before the need-handling. 
So it should be fine now for all possible page orders and page constructions.

**Comment by twodrops** [comment]
@danwos Works now as expected. Thanks for the quick fix.
