### ISSUE TITLE
Sphinx-Needs and parallel Sphinx build

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#319]
I do not have a concrete requirement for this yet, but do you think sphinx-needs could at some point support sphinx parallel builds `sphinx-build -j`? This means the read-phase when the needs model is created can be parallel and the extension sets `parallel_read_safe` to `True`

https://www.sphinx-doc.org/en/master/extdev/index.html

>The parallel-read-safe extension must satisfy the following conditions:
> - The core logic of the extension is parallely executable during the reading phase.
> - It has event handlers for env-merge-info and env-purge-doc events if it stores dataa to the build environment object (env) during the reading phase.

**Comment by danwos** [comment]
I would like to support this, but the problem is (afaik) that there is no data exchange between the different workers of a parallel sphinx-needs build.
Which means the important need-dictionary is not in sync and every worker is using a different one.

I made some tests in the past and I got quite fast errors like "need-id not found", "key error in ...".

## technical details
Sphinx parallel build starts for x documents a single worker in the writing event.

Due to the lack of an event just before the writing starts (maybe this has changed in the while),  Sphinx-Needs uses the first document event to do a lot of calculations on all needs (e.g. dynamic functions, back link, ...) and then sets a global flag, which indicates that this step does not need to be redone on the other document events.

So when Sphinx starts parallel workers, only `worker 0` would have the finished need-dict.
`worker 1-x` would still have the old version.

## own thoughts
I'm also not sure if the parallel option is a very good supported feature in the sphinx-extension world.
You need only one plugin, which does not support it and the benefit is gone.

I also have read some issue comments from Sphinx maintainers, that this feature is quite old, not very maintained and not used by them (status ~2 years ago).

But I would be happy to be wrong and I thing spending again some hours to figure out what needs to be done to get it running is a good idea.

**Comment by danwos** [comment]
First changes and tests are looking good and docs with needs and needtables only get already build.

Performance boost is not so high as expected (10% -15%).
But maybe the benefit is showing, when documents are getting more complex.
