### ISSUE TITLE
needextract rendering is broken for child needs

### ISSUE THREAD

**Issue by arnoox** [useblocks/sphinxcontrib-needs#329]
For a need `SOME_NEED` which has a child need, this code
```
   .. needextract::
      :filter: id in ['SOME_NEED']
```

Doesn't render the child need correctly. Only the text of the child need is displayed, but not as a need.

**Comment by danwos** [comment]
Thanks for reporting.

In the last days I have wrapped my head around this, as problems occur already on concept/architecture level.

We can not simply render a child need again, as this would create a copy and then we have 2 identical needs with the same id.

So for needs, created via ``needextract`` there must be a solution to manipulate the rst-content and replace each child-``need`` with a specific ``needextract`` for the need-id. Not sure if this is possible and will work in all cases.

Example:
**Source of needs**
```rst

.. req:: Test requirement
   :id: REQ_1

   Another, child requirement

   .. req:: Child requirement
     :id: REQ_1.1
   
      awesome child req.
   
   Some parent text
```
**Extract of needs**
```rst

.. needextract:: 
   :filter: id == "REQ_1"

```
**Needed replacement for content of REQ_1**

```rst
Another, child requirement

.. needextract:: 
   :filter: id == "REQ_1.1"

Some parent text

```

The problem with the not correct rendering is because of sphinx event system and the order, how directives gets resolved.
At first all needs get handled, then all other directives like ``needextract``.
So if ``needextract`` introduces a new need, then this gets not handled, as the needed function does not get called again by sphinx.
I hope this gets fixed as well, when we replace a child-need with a ``needextract``.

I will need some time to make some tests...

**Comment by PhilipPartsch** [comment]
Any updates on this?

**Comment by danwos** [comment]
No, I'm not happy with my solution from above and I have the fealing that it would be very unstable, as I see a lot of corner cases.
But I have no better idea....

**Comment by danwos** [comment]
The solution in #525 seems to work really well and I was so wrong with my above analysis.
