### ISSUE TITLE
Parallel filtering in needtable and co.

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#330]
Currently all needs are checked sequentially if they match a filter string.
For big projects with >5k needs and a lot of needtables this is quite a lot of checks.

I think the filtering can be done in parallel in multiple processes, as no data gets changed and not data has to be kept in sync between the different processes.
Only the results from the different processes needs to be merged.

This feature has nothing to do with the "sphinx parallel build" (-j option).
And even if sphinx gets executed on 1 core only, the filtering can be done in parallel.

**Comment by Thomas-Swindells-t** [comment]
I've been thinking on this, for my use-case at least, I'm finding a lot of my filters have a large amount of repetition, either with identical filters, or repeated fragment (type == x and ...). An obvious optimization therefore is not to keep repeating the same work.

I could see two ways this could be done (each with their own advantages).

1. Manual definition of shared expressions. This could be as simple as exposing lists of ids that were previously exported using export_id.  I can see two ways that these can then be referenced:
 a) a ':with: <export_id>' value on filterable directives, this would restrict the needs being evaluated by the other filter values to just those ones include in the export_id
 b) availability within a filter expression e.g. 'parent_need in exportId["export1"]'  
If we went this route I think it may also be useful to have an export only directive (could be adding a :hide: to needlist, repurposing needfilter for that functionality, or a new directive (needprepare? needdefine?)

2. Automatic optimization. Automatic caching of filter fragments (e.g. matching subsection of strings etc) so that if another expression shares the fragment then those rsults are reused rather than being recomputed. I've a suspicion that other than for a full exact match of expressions this probably would be a significant change in how expressions are currently evaluated.

**Comment by danwos** [comment]
Great ideas. 

I have made some profiling to figure out, where our bottleneck is.
Here is the needtable profiling for 100.000 needs on one single page:
![image](https://user-images.githubusercontent.com/998700/126126185-91c8403e-eccf-4a26-bb5c-42ed457709c2.png)

So overall handling the needtable-processing took only 41 seconds.
The overall build took ~37 minutes on my machine.
So saving some time on needtable processing brings not so much effort.

Also from the 41s, filtering took only ~0.5s:
![image](https://user-images.githubusercontent.com/998700/126126521-1e502602-806f-4176-bcf5-932a3c850901.png)

Defining the final table  took much more time (~33s, and ~22s are used by docutils).
So I think we should not spent time to optimize the filtering, as it is not currently our bottleneck.

To create your own profiling, just execute inside ``/performance/``:
```
python performance_test.py series --needs 100000 --pages 1 --needtables 1 --parallel 1 --profile NEEDTABLE  --snakeviz --debug
```

**Comment by danwos** [comment]
I close this, as I have the feeling that the benefit is not big enough and the needed development time could be spend better on other problems.
