### ISSUE TITLE
Not really working when requirement is put in included file

### ISSUE THREAD

**Issue by kl4m4** [useblocks/sphinxcontrib-needs#367]
When `.. req:: My first requirement` is placed in file that is later on included in eg. a `index.rst`, then after `make html` Sphinx gives me:
```
Sphinx error:
Needs could not generate a unique ID for a need with the title 'M y   f i r s t   r e q u i r e m e n t' because another need had the same title. Either supply IDs for the requirements or ensure the titles are different.  NOTE: If title is being generated from the content, then ensure the first sentence of the requirements are different.
```
For demonstration see [this repo I made to show my problem](https://github.com/kl4m4/sphinxcontrib.needs.problem). Checkout it and `make html`.
Am I missing something?

**Comment by danwos** [comment]
The problem is, that your files gets rendered twice by Sphinx.
Once, because it is a rst-file stored under the project root. So Sphinx find it and renders it, no matter that it is not included in any toctree.

The second time, because you  include it.

You can use [Sphinx exclude pattern](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-exclude_patterns), so that the first case will not happen.

Or you move the include-files out of the sphinx project.

**Comment by kl4m4** [comment]
Makes a lot of sense. Thank for your help!
