### ISSUE TITLE
Improve Needs JSON Structure

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinxcontrib-needs#409]
The current needs JSON structure uses Needs ID as part of the structure. The schema needs to be changed so that the content information is not the part of Needs JSON structure (schema). Such a static schema structure is expected by several reporting tools and such tools apply file-size limitations when dynamic jsons such as the current one are used.

Current Structure:

```
{
    "current_version": "1.0",
    "project": "Sample Project",
    "versions": {
        "1.0": {
            "needs": {
                "COMP_SYS_1": {
                    "asil": "A",
                    "id": "COMP_SYS_1"
		},
                "COMP_SYS_2": {
                    "asil": "D",
                    "id": "COMP_SYS_2"
		}
...
```

Expected Structure:

```
{
    "current_version": "1.0",
    "project": "Sample Project",
    "versions": {
        "1.0": {
            "needs": [
                {
                    "asil": "A",
                    "id": "COMP_SYS_1"
                },
                {
                    "asil": "D",
                    "id": "COMP_SYS_2"
                }
	]
...
```
As this will be a breaking change, export and import of both jsons might have to be supported for a while. Therefore a scheme-version might have to be written into the file as well.

```
{
  "schema_version": "1.0",
   "current_version": "1.0",
    "project": "Sample Project",
...
```

**Comment by danwos** [comment]
I have no problem to update the used json schema and have a versioned one.
But I don't understand the benefit from having a list instead of dict for ``needs``.

Being able to configure, which values shall be stored, is a great feature.
I have looked for a generic schema-solution, which allows the user to define its own structure.
But all the found libs are complex and an reimport may no work.
So I suggest a config var ``needs_json_file_exclude``, which takes a list of option-names, which shall not become part of the ``needs.json`` format. E.g. ``needs_json_exclude = ['status', 'content', 'budget']``

For the custom/updated schema, we maybe should allow to register own exporter-function, which can be called by its name.
Rough concept:
```python
from sphinxcontrib.needs.api import register_export

def my_exporter(needs, output, input):
    import json
    data = {
        "my": {
            "structure": needs
        }
    }
    
    json.dump(data, f"{output}/my_exporter.json")

def setup(app):
    register_export('exporter_name', my_export)
```
Then on cli: ``make exporter_name`` or ``sphinx-build -b exporter_name . _build/my_output``

This special exporter output can **not** be imported by Sphinx-Needs. For this the existing ``needs`` builder needs to be used.

For sure this exporter needs to be somehow "developed" and some dev-skills are needed. But it would also allow to transform the data to anything, also xml or csv/excel output, even a REST API call.
Maybe some default exporters can be already provided (e.g. for csv).

@twodrops : What do you think?
Is it fine for your case to provide the needed code to get the needed output-format on your own?

**Comment by twodrops** [comment]
@danwos Thanks for your ideas.

I guess it will be a nice feature to easily create multiple exporters for sphinx-needs. However, this is something which can also be easily done in python or using external means. In that sense, it is not very urgent to have this feature.

Regarding the current json structure, the problem I see is, the information that everything under "needs" is of the same type (that is a need type), is missing. In the current structure "needs" has inside it "different types" like COMP_SYS_1, COMP_SYS_2 etc. which is not true. They are all "needs" which can be addressed with keys like COMP_SYS_1, COMP_SYS_2 etc. Without clustering them in an array, we have a schema (a meta-model) which is continuously changing. This makes it tough for tools which need to work with a static schema to process the needs.json as it has an ever changing schema (COMP_SYS_1, COMP_SYS_2 etc.)

If we were to retain the dictionary, couldn't we think of the below structure which combines and array and a dictionary. The array signifies that the elements are of type "needs".

```
{
    "current_version": "1.0",
    "project": "Sample Project",
    "versions": {
        "1.0": {
            "needs":  [
                   "COMP_SYS_1": {
                    "asil": "A",
                    "id": "COMP_SYS_1"
		   },
                   "COMP_SYS_2": {
                       "asil": "D",
                       "id": "COMP_SYS_2"
		   }
                 ]
...
```
If this is true the same pattern applies to "versions" as well.

@Chriner Does the above structure help you, compared to the current one or is it completely absurd what I am saying here? :)

**Comment by Chriner** [comment]
The above structure is not valid. After "needs" the array starts and "COMP_SYS_1" is not a valid object in this case.
We are checking internally what kind of schema is needed.

**Comment by twodrops** [comment]
@Chriner Sorry for the wrong json syntax. I did not validate it. My bad!

In that case I can only think about the first structure I mentioned
```
{
   "current_version":"1.0",
   "project":"Sample Project",
   "versions":[
      {
         "version":"1.0",
         "needs":[
            {
               "asil":"A",
               "id":"COMP_SYS_1"
            },
            {
               "asil":"D",
               "id":"COMP_SYS_2"
            }
         ]
      }
   ]
}
...
```
I changed how "versions" are handled as well.

@danwos I feel the current needs JSON structure is mixing two meta-levels in one.  `current_version`, `project` etc. are in my opinion one meta-level and `COMP_SYS_1` and ``COMP_SYS_2` is a different meta-level (it is the instance level). The proposed structure above makes everything into the same meta-level. I don't know in deep about JSON , but I feel we should not use dynamic values as key in JSON (?). The keys shall be static and the values shall be dynamic. Else we cannot validate any JSON. This is also my understanding coming from XML. Within the internal python data structure, we could always create dictionaries out of this if needed right (with some assumption on what the key of the dictionary shall be, mostly an attribute called "ID")

**Comment by danwos** [comment]
Ahh, it took some time but finally I got your point. 
In this case I would say that also the field-names are some kind of "dynamic" information, so I would suggest to have something like:
```json
{
   "current_version":"1.0",
   "project":"Sample Project",
   "versions":[
      {
         "version":"1.0",
         "needs":[
            {
               "id":"COMP_SYS_1",
               "type": "requirement",
               "fields": [
                { 
                     "name": "asil",
                     "value": "A",
                     "type": "string"  # Okay, currently Sphinx-Needs only knows strings. But maybe for 1.0
                 },
                 {...} 
               ]
            },
         ]
      }
   ]
}

```
And maybe we should also export the complete (important) configuration:
* need types
* link types
* extra fields

So the json can "validate" itself and configuration changes between the versions are documented.

To be honest, I like and dislike this kind of format.
I like it, because it's clear.
But it is hard to work/code with it, as stuff can not be addressed directly by its name. You always have to loop through all elements to get the correct need or the needed field and its value.
