### ISSUE TITLE
IDs are forced to uppercase.

### ISSUE THREAD

**Issue by LeviD03** [useblocks/sphinxcontrib-needs#43]
Every identifier is force to uppercase when it is eventually stored in the needs.json file. This creates a discontinuity between the ID in RST and what the output contains. It causes difficulties when consuming the needs.json file from external scripts. Consumers can't rely on the ID in needs.json matching what is displayed in the HTML.

I suggest removing all the `.upper()` calls on IDs and links that way the plugin is not modifying the original content.

**Comment by danwos** [comment]
Good point.
But the IDs in needs.json and HTML should be both uppercase. Only the RST file may contain lowercase IDs.

However, I understand the problem and the decision of making it uppercase was based on the idea to get a common ID look in generated docs, even if multiple authors have set IDs in different ways.

Instead of only deactivating the upper() calls, I would like to introduce a new config parameter: needs_id_regex.
This config parameter needs a regular expression and each ID gets checked against it. If it does not match, no build is possible/warning gets thrown ( not sure what would be better).
If it match, the ID is taken as it is. So no more upper().
The default regex would allow upper characters, numbers and _ only.

This would higher the pressure in authors to always use the correct ID layout.

Would this support your use case?

Am 15. März 2018 21:52:36 MEZ schrieb LeviD03 <notifications@github.com>:
>Every identifier is force to uppercase when it is eventually stored in
>the needs.json file. This creates a discontinuity between the ID in RST
>and what the output contains. It causes difficulties when consuming the
>needs.json file from external scripts. Consumers can't rely on the ID
>in needs.json matching what is displayed in the HTML.
>
>I suggest removing all the `.upper()` calls on IDs and links that way
>the plugin is not modifying the original content.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/useblocks/sphinxcontrib-needs/issues/43

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by LeviD03** [comment]
Your proposal sounds great. To be clear, my main requirement (no pun intended) is that the IDs should appear in the needs.json output as they do in the RST, assuming they match the `needs_id_regex`. That seems to be the intention of your proposed changes, so I'm on board!

**Comment by danwos** [comment]
Ok, implemented given solution in 0.2.0 and released it today:
http://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-id-regex

Keep me informed, if you find any bugs and or the solution isn't working for you.
