### ISSUE TITLE
needs_types registered twice using add_need_type()

### ISSUE THREAD

**Issue by cedossanams** [useblocks/sphinxcontrib-needs#488]
Hi,

We are developing a sphinx need extension. When using the [add_need_type method](https://github.com/useblocks/sphinxcontrib-needs/blob/0.7.5/sphinxcontrib/needs/api/configuration.py#L34) to register types as follows for example:
>    add_need_type(app, "type1", "TY1", "TY1_", "#BFD8D2", "node")
>    add_need_type(app, "type2", "TY2", "TY2_", "#BFD8D2", "node")

We are getting warnings during the sphinx-build suggesting that:
> ...
> [app] adding directive: ('type1', <class 'sphinxcontrib.needs.directives.need.NeedDirective'>)
> WARNING: la directive 'type1' est déjà enregistrée, elle sera écrasée
> _translating: 'type1' directive is already registered, it will be overwritten_

It seems that, in the add_need_type method, the directive is:
1) [being appended to needs_type configuration](https://github.com/useblocks/sphinxcontrib-needs/blob/0.7.5/sphinxcontrib/needs/api/configuration.py#L64) which is, at config-inited state, [registered](https://github.com/useblocks/sphinxcontrib-needs/blob/master/sphinxcontrib/needs/needs.py#L427)
2) being immediatly registered ([add_directive](https://github.com/useblocks/sphinxcontrib-needs/blob/0.7.5/sphinxcontrib/needs/api/configuration.py#L65))
_So it is indeed registered twice_

As a temporary solution, we are currently doing method #1 (only append the new types to needs_type). We plan to use -W option to build our doc, meaning a warning fails the build*

Thanks

**Comment by danwos** [comment]
I understand the problem, but I'm not sure I understood the reason why it gets triggered.

Is the new type, registered via `add_need_type`, also available in `conf.py`?
Or gets it just registered by using the API?

Mhh maybe the reason is also the order of execution.
Your plugin should register stuff only if the original sphinx-configuration step is done.
So it should be called by a sphinx event:
`app.connect("config-inited", sphinx_needs_update)`

This is how  [Sphinx-Test-Reports](https://github.com/useblocks/sphinx-test-reports/blob/master/sphinxcontrib/test_reports/test_reports.py#L84) is doing it.

**Comment by cedossanams** [comment]
Hi @danwos,

Thank you very much for your quick reply !
> Is the new type, registered via `add_need_type`, also available in conf.py?
> Or gets it just registered by using the API?

Only registered using the API, no needs_types declared in our conf.py.

> Mhh maybe the reason is also the order of execution.
> Your plugin should register stuff only if the original sphinx-configuration step is done.
> So it should be called by a sphinx event:
> `app.connect("config-inited", sphinx_needs_update)`

Indeed it seems that all our configuration part was done before sphinx config-inited. I guess it could involved some conflicts. Connecting our setup to config-init state using the method you mentioned solved the issue.

I think we can close this
Thank you again.
