### ISSUE TITLE
Optional Need Titles?

### ISSUE THREAD

**Issue by tlovett** [useblocks/sphinxcontrib-needs#49]
We have a situation where we have a large number of existing guidelines for vendors written as requirements.  These all have IDs and descriptions, but they don't have unique titles.  We're in the process of migrating to this framework, but at this time the title is a required element as its a required argument of the directive.

It would be nice to be able to configure this behavior differently.   

Some ideas I've considered...
1. Simply making title optional via something like `needs_title_optional = True`
    Then you'd just write the need like this.
    ```
     .. req::
          :id: R-12345
          This is my requirement
    ```
    I think this is pretty clean to implement, but when the ID isn't provided you'd need to hash the 
    content instead of the title if one isn't provided. 

2.  Allowing the title to be treated as the ID.   Something like `needs_id_as_title = True`
    ```
     .. req:: R-12345
          This is my requirement
    ```
    I like the way this looks (at least for our use case).  However, similarly to above if 
   `needs_id_required = False`, then you have to hash the content.

Any other thoughts on this is a use case that could be supported or other ideas on how to handle it?  I'm more than happy to take a crack on the implementation if so...

**Comment by danwos** [comment]
Not having a title will be hard to handle internally, because the title is needed for the hash and it is also an import part of the needs templates.
Without a title the generated html side would look strange and maybe not work as expected (collapse function).
So the user should also change the templates, if not title is available. 
That's a huge task, which may lead to many, hard understandable problems for the user.

However, I understand your use case and see the need to find a solution for this.
So here is my proposal, let me know what you think:

1. There will be a global option "needs_title_required" and an need option as flag ":no-title:".
If one of this is set, a need does not need a title but some content!
2. A title gets automatically generated from the content, if no title is set by user.
Therefore we do not need to touch templates, hashing or other functions.
3. The title is based on the first sentence of the content.
4. We add a global option "needs_max_title_length", which is by default 0 and therefore deactivated.
5. If a title is longer as "needs_max_title_length", it gets cut after the last word that fits and some "..." are added.

Note: "needs_max_title_length" will be checked independently from "needs_title_required".
So it's a new functions, which has in general nothing to do with the "no title" problem, but is needed to not have too long, auto-generated titles from content.

What do you thing? Will this support your use case the right way?

**Comment by tlovett** [comment]
I think it can.  I can think of a few things that would need to be considered, and you may have already done that.

1. We may need to consider how the rendered content would read as there would be some duplication. 

    ![image](https://user-images.githubusercontent.com/6649/41852111-c96d7704-784f-11e8-9cba-100b776be9a8.png)
   
    Now, if that's not the behavior I want, I can override the template to get rid of the title, but by default that's what it would look like.  Alternatively, I guess the title could be suppressed in the doc if it's derived, and then just used in the other directives (`needtable`, `needflow`, etc.)

2.  The title doesn't currently get RST transformations (see the example above with `**shall**`). That's probably resolvable, but haven't looked at it.  The state machine is a little black magic to me at this point on what incantations will cause the content to be rendered properly, but I usually get there with a little trial and error.

3. There's also a chance content could make it into the title that you might not want (other directives, bulleted lists, etc.).  Then the content itself might be truncated. Probably ways to handle that (even with just guidance in the docs), but it's a consideration. 

I do think the `need_max_title_length` is a good addition as well.

My original idea what to allow the option to force the ID to be the title, and then tweak the templates to simply suppress the title, but I hadn't thought through the other directives (`needflow`, `needlist`, etc.) so  I think you're right that a derived title will be needed.  

My personal preference would be that if title is derived, then it should be suppressed in the default templates, but that's just a stylistic preference and I can tweak that via custom template easily enough.

Thoughts?

**Comment by danwos** [comment]
I agree that some kind of automatism for generating the title from content can produce fancy or problematic outputs.

In this case I have a new proposal:
1. option `needs_title_optional` and `:no-title:` as above.
2. If no title is given, need_info["title"] is set to "" (so that needfilter and co are working, but may look strange)
3. A new template is introduced `DEFAULT_TEMPLATE_NO_TITLE`, where the first line looks somehow like `{type}: ID {id}` (open for anything)
So both ways (title and no title) are supported in one sphinx project.
4. I still like the idea of taking the first sentences/paragraph automatically as title. It's like the first sentence in git message or the summary sentence in docstrings.
So maybe we can have an option `needs_title_from_content` and a need option `:title_from_content:` to support this, if no title is set by the user.
5. `need_max_title_length` as above

So this proposal supports 3 ways of writing needs:
* With a title
* With an automated title from the first sentence of content
* With absolutely no title

We may need to update the filter-directives a little bit to hide the title, if needed.
But that's another story :)

Does this work for you?

**Comment by danwos** [comment]
Good point.
Thought about this the last hours, because the template should be as simple as possible and using one or more templates would prevent us from inserting if statements.

However, I think the default template has already become complex, thanks to all the roles and more.
So yes, we should update our template or even better merge the COLLAPSE_TEMPLATE back to the default one, so that we only need to maintain one.

**Comment by danwos** [comment]
To be honest my current projects are taking too much time.
So I could implement this in 2-3 weeks.
Feel free to support here again :)
Otherwise we keep this issue open and I do my best to find some time...

**Comment by tlovett** [comment]
I don’t mind taking a crack at it - least I could do since I’m the one
asking for it ;-). Just didn’t  want check first.  Thanks for the review
and feedback.

**Comment by tlovett** [comment]
I think this can be closed now.  Any idea when 0.2.3 might get released to PyPI?  We're planning on using the optional title feature, and would like to pull that vs. pull it from source.

**Comment by danwos** [comment]
Ahh sorry, just forgot to release. It's done...
