### ISSUE TITLE
Dynamic function not found after registering

### ISSUE THREAD

**Issue by cilq** [useblocks/sphinxcontrib-needs#78]
I replicated the dynamic function example from the documentation but get the following error when building:

> Unknown dynamic sphinx-needs function

At the bottom of my conf.py I added the following lines

```python
def my_own_function(app, need, needs):
    return "Awesome"

needs_functions = [my_own_function]
```

In needs/needs.py built-in functions are registered with the environment but user functions with the application:

```python
        # Register built-in functions
        for need_common_func in needs_common_functions:
            register_func(env, need_common_func)

        # Register functions configured by user
        for needs_func in needs_functions:
            register_func(app, needs_func)
```

Registering user functions with the environment results in a pickling error and changing ```execute_func``` in needs/functions/functions.py to use ```env.app``` instead of ```env``` let's me use my custom function but prevents sphinx from finding the built-in ones.

**Comment by danwos** [comment]
Argh, sorry for the late response. I somehow overlooked this issue.
However, thanks for the detailed report and the code-diving to identify the exact problem. 

I have made some additional tests and it looked like sphinx tries to put all known configuration parameters to a pickle of the whole environment. And that for sure doesn't work with python methods, which are added to the **needs_functions**-list in conf.py.
So I added a workaround by not registering **needs_functions** inside sphinx and instead importing the parameter directly for my usage.
This seems to work and all related test cases are passed.

So the final usage of dynamic functions hasn't changed, so that your code/project should now run without any problem. If not please inform me.

I will create a new release shortly.
