### ISSUE TITLE
Subspecs displayed separately without TC links

### ISSUE THREAD

**Issue by danielvasas** [useblocks/sphinxcontrib-needs#91]
Version: 0.3.10

As is: the supbspecs are displayed separately from their respective mainspecs, but the test cases are linked to the main spec.

As it should be: 
* either the subspecs should not be displayd separately (the numbers on the links represent the subspec linking)
* or the subspecs should be rendered as linked (too) to their TC

To reprocude: git fetch https://asc-repo.bmwgroup.net/gerrit/ascgit307.test_execution_checker refs/changes/02/474302/14 && git checkout FETCH_HEAD

**Comment by danwos** [comment]
Thanks for the bug report.
I have made some change so that need_parts are directly connected to incoming links.
They are also now part of the part_need:
![image](https://user-images.githubusercontent.com/998700/59969078-c90f0e80-9545-11e9-899b-500099f85085.png)

Will create a new release in the next days....
